controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    odrive_controller:
      type: odrive_controller/ODriveController


odrive_controller:
  ros__parameters:
    # Joints: specify names of joints to be controlled
    joints:
      - arm

    # Passthrough [true, false]: if true, all values send will be directly passed to the hardware. Use this if the odrive itself is handling all control.
    passthrough: true
    # Mode [idle, position_filterd, position_trajectory, velocity_ramped, torque_control]: If passthrough is used, specify which mode to configure the odrive to.
    mode: torque_control

    gains:
      arm: {
        "position_p": 30.0, "position_i": 0.0, "position_d": 0.0, "position_output_min:": -10.0, "position_output_max:": 10.0,
        "velocity_p": 0.2, "velocity_i": 4.0, "velocity_d": 0.0, "velocity_output_min:": -.inf, "velocity_output_max:": .inf,
      }
