#ifndef ODRIVE_CONTROLLER__ODRIVE_CONTROLLER_HPP_
#define ODRIVE_CONTROLLER__ODRIVE_CONTROLLER_HPP_


// #include "controller_interface/chainable_controller_interface.hpp"
// #include "realtime_tools/realtime_thread_safe_box.hpp"
// #include "std_msgs/msg/float64_multi_array.hpp"
// auto-generated by generate_parameter_library

#include "controller_interface/controller_interface.hpp"
#include "odrive_ros2_control_example/odrive_controller_parameters.hpp"

namespace odrive_controller
{
class ODriveController : public controller_interface::ControllerInterface
{
public:
  ODriveController();
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(const rclcpp::Time & time, const rclcpp::Duration & period) override;
  controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::vector<std::string> reference_interface_names_;
  std::vector<std::string> command_interface_names_;

  // std::shared_ptr<ParamListener> param_listener_;
  // Params params_;

  // realtime_tools::RealtimeThreadSafeBox<DataType> rt_buffer_;
  // DataType command_;
  // rclcpp::Subscription<DataType>::SharedPtr joints_cmd_sub_;
};

}  // namespace odrive_controller

#endif  // ODRIVE_CONTROLLER__ODRIVE_CONTROLLER_HPP_
